### ISSUE TITLE
Can't open user.dat

### ISSUE THREAD

**Issue by Julian-Hochhaus** [beckstev/learning-programm-physics-3-4#4]
Tested with clean installation. It seems like user.dat isn't created as table.
Error occurs while running prepare.py. user.dat is created but without table-like structure. 
Dunno how to fix it.
Error msg:
Traceback (most recent call last):
  File "prepare.py", line 254, in <module>
    user.name(user_name)
  File "prepare.py", line 30, in name
    userCursor.execute(""" SELECT COUNT ( fragenrichtig ) FROM user WHERE name = "{}" """.format(User.username))
sqlite3.OperationalError: no such table: user

**Comment by beckstev** [comment]
Did you run _user.py_ first? 
This command going to create _user.dat_.

Only for _gui.py_ it is not necessary, **at the moment**, to create _user.dat_.

**Comment by Julian-Hochhaus** [comment]
Running user.py fixed my problem.
Thank you :100:

**Comment by beckstev** [comment]
Great, enjoy learning.
